
services:
  postgres:
    image: postgres:17.2-alpine
    container_name: carflow-postgres
    environment:
      POSTGRES_DB: carflow_db
      POSTGRES_USER: carflow_user
      POSTGRES_PASSWORD: carflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local