spring:
  application:
    name: carflow

  datasource:
    url: jdbc:postgresql://localhost:5432/carflow_db
    username: carflow_user
    password: carflow_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true